### ISSUE TITLE
__str__ მეთოდი შეგიძლია გადაუტვირთო, საკმაოდ ხშირად გამოიყენება

### ISSUE THREAD

**Issue by MariamKipshidze** [gigasamkharadze/tbc-book-shop#1]
https://github.com/gigasamkharadze/tbc-book-shop/blob/6f8ed5b7df76ad3b672df9c5675e7be504ecc574/market/models.py#L5

**Comment by gigasamkharadze** [comment]
def __str__(self):
        return f'{self.name} written by {self.author_name}'
